### ISSUE TITLE
Testing gmail notification

### ISSUE THREAD

**Issue by brntbeer** [brntbeer/test-notifications-gmail-again#1]
hey @deanmunslow  @danielmarconetto. this notification should go to your email. feel free to reply to that.

**Comment by deanmunslow** [comment]
Hi

**Comment by brntbeer** [comment]
@danielmarconetto what is going on =(

**Comment by DanielMarconetto** [comment]
Yo from gmail

On Tuesday, 8 March 2016, Brent Beer notifications@github.com wrote:

> hey @deanmunslow https://github.com/deanmunslow @danielmarconetto
> https://github.com/danielmarconetto. this notification should go to
> your email. feel free to reply to that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brntbeer/test-notifications-gmail-again/issues/1.

## 

Best Regards,

Daniel Marconetto
GitHub UK & Ireland
+44 07900 188233
danielmarconetto@github.com

https://enterprise.github.com/case-studies

**Comment by brntbeer** [comment]
RIP anything other than gmail. Long live the king.
